# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
environment_variables:
    plaintext:
        S3_BUCKET: "angular-ucp-calendar"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
    build:
        commands:
            - echo Build started on `date`
            - ng build
    post_build:
         commands:
            - aws s3 cp dist/calendario s3://angular-ucp-calendar --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
